config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
  	#we can not have two roots in route hence rename it
  	root 'notes#index', as: "authenticated_root"
  end

  get '/notes/hashtag/:name', to: 'notes#hashtags'

  root 'welcome#index'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# class ApplicationRecord < ActiveRecord::Base
#   #self.abstract_class = true
# end

app/models/note.rb
class Note
  include Mongoid::Document
  # this gives us created_at and updated_at funtions for notes
  include Mongoid::Timestamps 

  field :title, type: String
  field :content, type: String

  belongs_to :user
  has_and_belongs_to_many :tags

  
  after_create do 
  	note = Note.find_by(id: self.id)
  	hashtags = note.content.scan(/#\w+/)
  	hashtags.uniq.map do |hashtag|
  		tag = note.tags.find_or_create_by(name: hashtag.downcase.delete('#'))
  		tag.save!
  	end
  end

  after_update do 
  	note = Note.find_by(id: self.id)
  	note.tags.destroy_all
  	hashtags = note.content.scan(/#\w+/)
    	hashtags.uniq.map do |hashtag| 
  		tag = note.tags.find_or_create_by(name: hashtag.downcase.delete('#'))
  		tag.save!
  	end
  end

end

app/models/tag.rb
class Tag 
	include Mongoid::Document
 	include Mongoid::Timestamps
 	include Mongoid::Attributes::Dynamic

	field :name, type: String
	has_and_belongs_to_many :notes
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  has_many :notes

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit, :update, :destroy]
	def index
		@notes = Note.where(user_id: current_user)
	end

	def show
		
	end

	def hashtags
		tag = Tag.where(name: params[:name])
		@notes = []
		tag.each do |t|
			@notes << t.notes
		end
	end

	def new
		@note = current_user.notes.build
	end

	def create
		@note = current_user.notes.build(note_params)
		if @note.save
			redirect_to @note
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @note.update_attributes!(note_params)
			redirect_to @note
		else
        	redirect_to 'edit'
        end
	end

	def destroy
		@note.destroy
		redirect_to notes_path
	end

	private

	def find_note
		@note = Note.find(params[:id])
	end

	def note_params
		params.require(:note).permit(:title, :content)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title NoteNote | Your online Notebook
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
  = csrf_meta_tags 
%body
  %header
    .header_inner
      %h1 NoteApp
      %nav
        - if user_signed_in?
          = link_to "New Note", new_note_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path  
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit

app/views/notes/edit.html.haml
%h1 Edit Your Note

= render 'form'

= link_to "Cancel", note_path

app/views/notes/hashtags.html.haml
.wrapper_with_padding
	- unless @notes.blank?
		- @notes.each do |note|
			- if note.present?
				%a{ href: (url_for [note.first])}
					%p.title= note.first.title
	- else
		%h2 Add a note
		%p It looks like you haven't created any notes yet.... Lets fix that. Why don't you create a new note below.
		%button = link_to "New Note", new_note_path

app/views/notes/index.html.haml
.wrapper_with_padding
	- unless @notes.blank?
		- @notes.each do |note|
			%a{ href: (url_for [note])}
				%p.title= note.title
	- else
		%h2 Add a note
		%p It looks like you haven't created any notes yet.... Lets fix that. Why don't you create a new note below.
		%button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
%h1	Add a New Note

= render 'form'

app/views/notes/show.html.haml
%h1= @note.title
- @note.tags.each do |t|
	%h2= link_to '#' + t.name, '/notes/hashtag/' + t.name
%p= @note.content

= link_to "All Notes", notes_path
= link_to "Edit", edit_note_path(@note)
= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?"}

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 NoteApp
		%p Your online notepad. Always handy.
		%button= link_to "Sign Up", new_user_registration_path